# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idw <- function(coords_pred, coords_vals, vals, p) {
    .Call(`_SpatialBSS_idw`, coords_pred, coords_vals, vals, p)
}

k_mat_ball <- function(coords, h) {
    .Call(`_SpatialBSS_k_mat_ball`, coords, h)
}

k_mat_ring <- function(coords, h1, h2) {
    .Call(`_SpatialBSS_k_mat_ring`, coords, h1, h2)
}

k_mat_exp <- function(coords, h) {
    .Call(`_SpatialBSS_k_mat_exp`, coords, h)
}

k_mat_ball_angle <- function(coords, h, am, tol) {
    .Call(`_SpatialBSS_k_mat_ball_angle`, coords, h, am, tol)
}

k_mat_ring_angle <- function(coords, h1, h2, am, tol) {
    .Call(`_SpatialBSS_k_mat_ring_angle`, coords, h1, h2, am, tol)
}

k_mat_exp_angle <- function(coords, h, am, tol) {
    .Call(`_SpatialBSS_k_mat_exp_angle`, coords, h, am, tol)
}

idx_per_block <- function(coords, coords_block, d) {
    .Call(`_SpatialBSS_idx_per_block`, coords, coords_block, d)
}

sp_lcov_sparse <- function(x, k) {
    .Call(`_SpatialBSS_sp_lcov_sparse`, x, k)
}

sp_ldiff_sparse <- function(x, k) {
    .Call(`_SpatialBSS_sp_ldiff_sparse`, x, k)
}

